//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractMonthlyClaimSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public System.Guid ClaimID { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public string ClaimDocumentPath { get; set; }
        public string Status { get; set; }
        public System.Guid UserID { get; set; }
        public string AdditionalNotes { get; set; }
    }
}
